Avoid to exit in matlab postinstall script.
It could block another postinstall script to be executed after.

diff --git a/misc/binpkg_postinst_scripts/debrpm/postinst_matlab.sh.in b/misc/binpkg_postinst_scripts/debrpm/postinst_matlab.sh.in
--- a/misc/binpkg_postinst_scripts/debrpm/postinst_matlab.sh.in
+++ b/misc/binpkg_postinst_scripts/debrpm/postinst_matlab.sh.in
@@ -8,10 +8,13 @@ function dirname_noerr {
 MATLAB_ROOT=$(dirname_noerr $(dirname_noerr $(which matlab 2>/dev/null)))
 [[ ! -d "${MATLAB_ROOT}" ]] && MATLAB_ROOT=$(dirname_noerr $(dirname_noerr $(find /usr/local -maxdepth 10 -type f -name "matlab" | tail -n 1)))
 [[ ! -d "${MATLAB_ROOT}" ]] && MATLAB_ROOT=$(dirname_noerr $(dirname_noerr $(find /opt/ -maxdepth 10 -type f -name "matlab" | tail -n 1)))
-[[ ! "$?" = 0 || ! -d "${MATLAB_ROOT}" ]] && echo "Can't find Matlab root dir. Add MATLAB_ROOT/bin to the PATH environment variable (of root user)." >&2 && exit 1
-STARTUP_DIR="${MATLAB_ROOT}/toolbox/local/"
-STARTUP_FILE=${STARTUP_DIR}/startup.m
-[[ -r "$STARTUP_FILE" ]] && grep -i -v faust "$STARTUP_FILE" > "$STARTUP_FILE"
-FAUST_MATLAB_WRAPPER_PATH="@CMAKE_INSTALL_MATLAB_PREFIX@"
-echo "addpath(genpath('"$FAUST_MATLAB_WRAPPER_PATH"'))" >> "$STARTUP_FILE"
-
+if [[ ! "$?" = 0 || ! -d "${MATLAB_ROOT}" ]]
+then
+	echo "Can't find Matlab root dir. Add MATLAB_ROOT/bin to the PATH environment variable (of root user)." >&2
+else
+	STARTUP_DIR="${MATLAB_ROOT}/toolbox/local/"
+	STARTUP_FILE=${STARTUP_DIR}/startup.m
+	[[ -r "$STARTUP_FILE" ]] && grep -i -v faust "$STARTUP_FILE" > "$STARTUP_FILE"
+	FAUST_MATLAB_WRAPPER_PATH="@CMAKE_INSTALL_MATLAB_PREFIX@"
+	echo "addpath(genpath('"$FAUST_MATLAB_WRAPPER_PATH"'))" >> "$STARTUP_FILE"
+fi
